### PR TITLE
Allow submitting Notable Person quotes

### PR DESCRIPTION
**Pull request by forabi**

### CODE REVIEW

**Comment by forabi** [comment]
I just want to take some time to decide on the best way to handle errors. Many articles recommend differentiating between user errors (which should be returned as a regular result) and server errors which should be thrown. This makes sense, but I think there are some places where we would not be able to treat errors as data. For example, the `viewer` query has the `@requireAuth` directive. Using directives is great because it encourages separation of concerns and re-usability of code, but it seems to go against with this idea of treating user errors as data. If we were to do that, we would need to move the logic from `requireAuth` back into the `viewer` query resolver, because that resolver now has to know if the user is authenticated or not to return a proper success or error result.

**Comment by forabi** [comment]
I thought about this and I think it's beneficial to have user errors returned as regular types instead of being thrown, even if we cannot do that everywhere. The only problem is that we have some older mutations (`createNotablePerson` and `createUser`) that currently throw errors and updating them to return error types is a breaking change. It's fine though, because those mutations are not really used anywhere yet.

**Comment by forabi** [comment]
The test suites can be streamlined with more helpers for authentication (we might need some sort of in-memory authentication provider), but I think this should go in another PR.

**Comment by wholesomedev** [comment]
> The only problem is that we have some older mutations (createNotablePerson and createUser) that currently throw errors and updating them to return error types is a breaking change.

GraphQL website used to have language that said something like "before you start implementing your GraphQL API, think long and hard about how you want your API to look like because in GraphQL you shouldn't have versions and you shouldn't have breaking changes", which I thought sounded very wrong for software development.

But I just checked the website again and it looks like that language was removed.

What the website seems to suggest now is that we don't need to have breaking changes in GraphQL because we can simply expand our schema, which makes more sense. However, (and I'm talking out of complete ignorance here) I wonder if we should have versions at the root level in our schema?

For example...

```js
{
  v1: {
    createNotablePerson
  },
  v2: {
    createNotablePerson
  }
}
```

That way, we can add new things without having to think of new names just to avoid conflicts with existing names.

**Comment by forabi** [comment]
> GraphQL website used to have language that said something like "before you start implementing your GraphQL API, think long and hard about how you want your API to look like because in GraphQL you shouldn't have versions and you shouldn't have breaking changes", which I thought sounded very wrong for software development.

When I talk about breaking changes, I do not mean maintaining backwards compatibility is a good practice for API development. While I do think this statement is true, I think we are in a too early stage to worry about backwards compatiblity.

What I mean is that changing the return type of a query we are currently using in production would literally break the website until we update the code consuming that query and push a new version. That's why we have checks like `findBreakingChanges` in place.

> However, (and I'm talking out of complete ignorance here) I wonder if we should have versions at the root level in our schema?

I don't think that will work. The two different versions will have conflicting types because types do not have a scope (they are global across the entire GraphQL schema). So we would need to define `NotablePerson_v1`, `NotablePerson_v2`... etc.

If we really want to introduce a version of some query, because we could not expand the existing query, it might make more sense to just add a new version of that query alone:

```
mutation {
  createUser() {
    id
  }
  createUser_v2() {
    result {
      state
    }
  }
}

```

Deprecating fields and types also helps. In the mutation above, we might be able to sneak the changes in the same mutation by keeping `id` and deprecating it, and expanding the return type with `result`.

**Comment by forabi** [comment]
> which I thought sounded very wrong for software development.

Interesting. I've always believed breaking API changes are bad. For a service as large as Facebook with billions of users querying the same GraphQL API on thousands of different devices (many of them could be running outdated versions of the Facebook app), it makes a lot of sense to me that they never allow any breaking changes.

**Comment by wholesomedev** [comment]
>I don't think that will work. The two different versions will have conflicting types because types do not have a scope (they are global across the entire GraphQL schema). So we would need to define NotablePerson_v1, NotablePerson_v2... etc.

Ah, okay. Makes sense. I just wanted to avoid the `_v1` and `_v2` postfix because it's ugly. But if that's how it has to be, then ok.

>Interesting. I've always believed breaking API changes are bad. For a service as large as Facebook with billions of users (and developers) querying the same GraphQL API on thousands of different devices (many of them could be running outdated versions of the Facebook app), it makes a lot of sense to me that they never allow any breaking changes.

Yes, I fully agree that breaking changes are bad. But saying that we should neither have versions nor breaking changes doesn't make sense. We'll either have to have versions, or breaking changes within the same version.

**Pull request merged**
